name: Build
on:
  push:
    branches: [ main ]
jobs:
  book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo install mdbook
      - run: ./scripts/parse_and_build.sh
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: book
          github_token: ${{ secrets.GH_TOKEN }}
